### PR TITLE
feat: ignore gh-pages events

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)

@nhcarrigan I wasn't sure how to test this, so it may not be great.  Do you have a way of testing things or should we just try it and hope?

### CODE REVIEW

**Comment by nhcarrigan** [comment]
So I usually test by spinning up a local chat instance, setting the webhook up, and CURLing some mock data.

**Review by naomi-lgbt — APPROVED** [review]
This is still a draft, but giving this some quick testing and appears to function as intended.

**Comment by ojeytonwilliams** [comment]
Cheers, Nick, I've tried it out myself and it seems to work.  Do you want to do the honours or shall I?

**Comment by nhcarrigan** [comment]
Will get this deployed 🙂

**Pull request merged**
